games-on-whales/gow

configs/pulseaudio/daemon.conf
This way playing a game, exiting, then reconnecting some time later won't fail due to missing pulse.
=> Disable Pulseaudio's idle exit

.dockerignore, README.md, configs/xorg-nvidia.conf, ensure-nvidia-xorg-driver.sh, gpu.Dockerfile, startup-gpu.sh
This is one possible way to do this. What do you think?
If you launch the container in the `nvidia-docker` runtime, the startup process will try to ensure you have an appropriate Xorg driver installed.  It will look for one in `/usr/lib/x86_64-linux-gnu/nvidia/xorg` (which is where the Ubuntu package installs the driver), and it will look in `/nvidia/xorg` (where you can use Docker to map in your host's driver, or another specific version).
If it doesn't find one in one of those locations, it tries to identify an Ubuntu package with the same exact version as the host's driver.  If it can find such a package, it installs it.  If it can't, it prints a failure message.  It will still _attempt_ to launch Xorg in this case, but it warns that it may fail.
If you want to skip all this and just …
=> Add a script to automatically install the Nvidia Xorg driver if possible

README.md, images/xorg/scripts/ensure-nvidia-xorg-driver.sh
Also speed up the install script by using `dpkg-divert` instead of building a dummy package to provide the mapped-in driver functionality.
=> install both nvidia libraries needed by xorg

.github/workflows/docker-build.yml, images/pulseaudio/Dockerfile, images/retroarch/Dockerfile, images/steam/Dockerfile, images/sunshine/Dockerfile, images/udevd/Dockerfile, images/xorg/Dockerfile
This PR adds the following features to the build actions:
- upload to GitHub Container Registry in parallel to Docker Hub. This requires:
- create a token for GHCR - see [instructions](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry)
- github repository secrets:
- GHCR_USERNAME
- GHCR_TOKEN
- multiarch support (steam and shunsine do not build on arm64 yet so disabled)
- cache: cache latest build
- nightly builds
- new tags:
- stable versions using semver - tag with v1.0.0 (or better, [draft a release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository))
- edge: latest commit to master branch (build on each push or …
=> add GHCR, mutiarch and cache

docker-compose.yml
Without this some emulators such as Dolphin crash.
See https://github.com/libretro/dolphin/issues/222
Related Helm chart fix: https://github.com/k8s-at-home/charts/pull/1142
=> increase SHM for retroarch

.github/workflows/docker-build.yml
Also supports explicitly setting the docker hub org with the secret DOCKERHUB_ORG. 
@ABeltramo , would you consider setting DOCKERHUB_ORG to gameonwhales so we can remove the special code for it?
=> correct checking for games-on-whales

compose/headless.yml
When I moved the `udev` volume to `docker-compose.yml`, I forgot to check in the change that _removed_ it from this file.  Oops!
=> Remove redundant `udev` volume

run-gow
Fixes #81.
Also adds some extra info to the `--debug` output (docker compose version, detected OS).
=> Fix version comparison to be >=, add some more debugging info

run-gow
it was breaking os detection for distros with `/etc/lsb-release`
=> remove extra space from assignment

.github/workflows/docker-build-and-publish.yml
Apparently the built-in github token isn't allowed to publish packages :sob:
=> undo last change

.github/workflows/lint.yml, images/base-app/Dockerfile, images/base/build/setup-retro-user, images/base/scripts/bootstrap.sh, images/base/scripts/lib/utils.sh, images/pulseaudio/Dockerfile, images/retroarch/Dockerfile, images/steam/Dockerfile, images/sunshine/Dockerfile, images/udevd/Dockerfile, images/xorg/Dockerfile, images/xorg/scripts/ensure-nvidia-xorg-driver.sh
Added an action to run linters for shell scripts and Dockerfiles.  It will run on any PR.  If there's a lint issue in one of the files being modified, it will add a review pointing out the specific line and error. If it finds errors in files _not_ in the PR, those will get noted under the "Checks" tab.  None of this blocks merging the PR anyway, but it should make it much easier to spot potential problems.
=> Add an action to lint shell scripts and Dockerfiles

docker-compose.yml, images/sunshine/Dockerfile, images/sunshine/configs/apps.json
For now, we're just installing the `.deb` package included in the official image. Later, we can work towards a tighter integration.
=> use the official sunshine image instead of building ourselves

images/sunshine/Dockerfile
As of Sunshine v0.18.0 we now have images for various Linux distros and versions.
This PR updates the sunshine tag to use the `ubuntu-22.04` image, which is the equivalent of the previous single image.
More info here: https://hub.docker.com/r/lizardbyte/sunshine
=> update sunshine tag to `lizardbyte/sunshine:v0.18.1-ubuntu-22.04`

run-gow
* Search for `user.env` in `$HOME/.config/gow/user.env`, falling back to `./user.env` if it doesn't exist. This way, modifications to `user.env` are separate from the git repo.
* If `$HOME/.config/gow/run-gow-rc` exists, read a set of default arguments from it, merging them with the arguments provided on the command line.  This helps make command lines shorter and easier to remember and type, especially since many arguments are specific to the host environment and will hardly ever change.
=> Add support for default arguments to `run-gow`

images/xorg/scripts/ensure-nvidia-xorg-driver.sh
us.download.nvidia.com doesn't work anymore, but without the us, the links work fine. 
e.g. 
404: https://us.download.nvidia.com/XFree86/Linux-x86_64/525.60.13/NVIDIA-Linux-x86_64-525.60.13.run
200: https://download.nvidia.com/XFree86/Linux-x86_64/525.60.13/NVIDIA-Linux-x86_64-525.60.13.run
=> Fix nvidia driver download URL

images/retroarch/Dockerfile
Example of the core crash:
After installing core progresses further but still hangs:
=> Adding missing packages to RetroArch Dockerfile - partially-fixes Dolphin core and fixes PCSX2

.github/workflows/auto-build.yml, images/base/Dockerfile, images/retroarch/scripts/startup.sh, images/sunshine/Dockerfile
Fixes #136. I have verified that this will install and start up cleanly on ARM (using Oracle Cloud). I have _not_ attempted to actually connect to the running Sunshine instance because I didn't want to deal with the network setup.
=> enable arm64 builds for base, sunshine, retroarch

images/base/overlay/etc/cont-init.d/10-setup_user.sh
by ensuring there's only one user with the preferred UID
Originally discussed in Discord:
> it happens when the container starts up and tries to change the default user's UID/PID based on the environment. basically if you use a UID that already exists (which we do by default) it ends up adding a second user with the same ID and a different $HOME. then when steam (or whatever) tries to get the home dir for its user id it gets the home dir of the older user, which in this case is wrong.  it can be fixed by actually changing the user's UID instead of creating a second user
=> fix containers using the wrong home dir

images/steam/Dockerfile, images/steam/scripts/startup.sh
The steamdeck mode we were currently using has problems starting up with the debian packages bootstrap install.
We originally used that mode for the new UI and a bunch of steam deck specific features.
These days the desktop bigpicture mode has catched up and updates fine on initial launch.
So lets switch to that (and sadly disable the Xwayland separation from gamescope as normal steam won't use that causing black screens in games).
=> steam: initial startup

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/lutris.adoc, images/base-app/scripts/launch-comp.sh, images/lutris/Dockerfile, images/lutris/configs/lutris-lutris.conf, images/lutris/configs/lutris-system.yml, images/lutris/scripts/startup-10-create-dirs.sh, images/lutris/scripts/startup.sh
This PR would add a new container image for lutris.
Lutris contains a mechanism to install software via yaml scripts. This PR leverages this feature to enable the creation of images specialised for specific applications. (see lutris-supertux for an example).
I've moved several key lutris directories into /var/lutris/, this is to make it possible for multiple containers to share the same set of installation files. 
I've also changed the launcher script in the base-app image to be able to specify command-line arguments to the application to be launched.
suggested wolf config.toml snippet;
```toml
[[apps]]
title = "Lutris"
start_virtual_compositor = true
[apps.runner]
type = "docker"
name = "WolfLutris"
image = "gow/lutris"
mounts = ["lutris-games:/var/lutris/:rw"] # Adjust this based on …
```
=> Implement a lutris container.

images/base-app/configs/sway/config
Meta key requires a setting change in moonlight client to properly work, ALT can works OOTB
=> Replace "Meta" key with "ALT"

images/base-app/Dockerfile, images/steam/Dockerfile
Some games with native Linux ports (like Half-Life 2: Deathmatch) seem to require `en_US.UTF-8` locale to be available regardless of the user's language setting:
This makes docker generate that locale at image build time, and leaves the `locales` package installed so the user can generate any others required.
=> Install the `locales` package in the steam image and generate en_US.UTF-8

images/steam/Dockerfile, images/steam/scripts/startup.sh
Since Mangoapp is already running in Gamescope, I figured [MangoHud](https://github.com/flightlessmango/MangoHud/) makes sense for Sway.
I have no idea *where* to document this. The current Wolf documenation doesn't mention MangoApp anywhere.
But in order for this to be useful, users need to know to press `Right Shift + F12` to make the overlay show up, and `Right Shift + F11` to change the position of the overlay (shows up in the top left by default).
=> feat: Add MangoHud support to Steam images running Sway

images/steam/Dockerfile, images/steam/steamos-session-select
The "Exit Steam" button disappears when running in gamescope, so this is the only way I can think of to quit properly.
=> Make gamescope's "Switch To Desktop" quit steam

images/lutris/Dockerfile
To be able to use winetricks within Lutris image there are two packages needed:
- winetricks
- zenity
This PR include both packages in the Lutris image Dockerfile
=> Added winetricks and zenity packages to Lutris image

images/heroic-games-launcher/scripts/startup.sh
Proposal of adding startup flags variable for Heroic Launcher. Tested and working.
Startup flags are needed when you want to automatically start a game like this from config.toml:
```
[[apps]]
start_virtual_compositor = true
title = "Desperados III"
[apps.runner]
base_create_json = """
{
"HostConfig": {
"IpcMode": "host",
"CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
"SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
"Ulimits": [{"Name":"nofile", "Hard":10240, "Soft":10240}],
"Privileged": false,
"DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
}
}
"""
ports = []
devices = []
env = [
"PROTON_LOG=1",
"RUN_SWAY=true",
"TZ=Europe/Warsaw",
"GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*", …
```
=> Startup flags variable for Heroic Launcher

images/retroarch/Dockerfile
#195 details missing dependencies when trying to launch the LRPS2 core in the RetroArch image.
Log line that points to the issue:
```
[ERROR] Failed to open libretro core: "/home/retro/.config/retroarch/cores/pcsx2_libretro.so"
[ERROR] Error(s): libGLU.so.1: cannot open shared object file: No such file or directory
```
The missing dependencies can be checked and confirmed by running `ldd ~/.config/retroarch/cores/pcsx2_libretro.so`, which reveals the following in it's output:
```
libGLU.so.1 => not found
libaio.so.1 => not found
```
This PR installs `libglu1` and `libaio1t64`, and creates a symbolic link of `libaio.so.1t64` as `libaio.so.1`, thus resolving the missing dependencies.
=> RetroArch LRPS2 core missing dependencies

images/es-de/Dockerfile
This changes the static build for RPCS3 in ES-DE and moves it to the latest release.
I still need to test and want to do the other emulators in the file.
=> Update RPCS3 with rolling release

.github/workflows/auto-build.yml, .github/workflows/docker-build-and-publish.yml
@ABeltramo  close previous https://github.com/games-on-whales/gow/pull/205
to enable selfHosted runner as a organization Member with this PR
thank you :+1: 
EDIT: will sign my commit before merge dw
=> Enable automatic build of images for ARM

.github/workflows/auto-build.yml, images/prismlauncher/Dockerfile, images/prismlauncher/scripts/startup.sh
I included a fully functional PrismLauncher image that supports all Java versions used by Minecraft, ensuring compatibility with every version from Alpha to the latest 1.21.
Note: Since the image doesn't include a browser, you'll need to use another device, like a phone, to connect to your Microsoft account. However, this should only be necessary the first time you connect, as everything appears to save correctly afterward.
I'm successfully running Minecraft 1.21 with shaders on a 3060 Ti using proprietary drivers.
https://github.com/user-attachments/assets/478aef23-4814-4135-8cc4-5854540df8bb
=> Added prismlauncher as an image

images/kodi/Dockerfile, images/kodi/overlay/etc/cont-init.d/99-startdbus.sh, images/kodi/scripts/startup-10-create-dirs.sh, images/kodi/scripts/startup.sh
A complete redo of the Kodi image via system wide Flatpak install.
This PR makes #212 obsolete.
This image contains all Addons that come bundled with the Flatpak version of Kodi.
Some Addons may be disabled at first start, and can be enabled later.
Testing and feedback is always welcome ;-)
=> Kodi image via Flatpak

apps/heroic-games-launcher/build/Dockerfile
They changed the release filename
Before:
heroic_2.15.2_amd64.deb
Now:
Heroic-2.16.0-linux-amd64.deb
=> The filename of heroic release file don't have underscore anymore

images/pulseaudio/build/configs/default.pa
I don’t know if this PR is right so I need some help, fill free to correct me.
I will try to explain the best way I can.
I had a problem that my audio didn’t work with native linux games, but with wine worked. 
I tried with two native games, Minecraft and Valheim, the problem was that these games were choosing the wrong audio output, because inside of Minecraft audio config I had to change the output to "null output #2" for it to work, sadly Valheim don't have this option in the game.
I don’t know much about Pulseaudio so I tried to search a bit about this, and I tried messing with the config files, and when I tested commenting the line of "load-module module-null-sink" all the games worked e I don't even know why 😂
After changing this I tested the audio of Firefox, Steam and Heroic …
=> fix: native linux games with the wrong audio output

images/base/build/Dockerfile
Mesa-25 is required for newer graphics cards, such as AMD's Radeon RX 9070.
This adds [oibaf:ppa](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) repository to the base image. Subsequent images will then pull the newer version of mesa.
Tested on my local machine building docker images for: base, base-app, base-emu, steam, and a custom pegasus.
=> Feature: Mesa-25 from oibaf:ppa

.github/workflows/mirror-repo.yml, apps/heroic-games-launcher/build/Dockerfile, apps/steam/build/Dockerfile, images/base-app/build/Dockerfile, images/base/build/Dockerfile, images/base/build/overlay/opt/gow/bash-lib/utils.sh
Since PrismLauncher brings support for Mangohud and it's definitely better than Minecrafts F3 debug overlay, we should include it in the image.
=> feat: added mangohud to required packages

apps/pegasus/_index.md, apps/pegasus/build/Dockerfile, apps/pegasus/build/configs/app/game_dirs.txt, apps/pegasus/build/configs/app/metadata.pegasus.txt, images/base-emu/build/launchers/rom_launcher.sh
- Added the "rom_launcher" back into the system as the mounting logic is in this script. It is in the "base-emu" image.
- Updated the documentation to explain how to use it.
- Updated the game_dirs.txt to include the new scummvm reference
- Updated the default metadata.pegasus.txt to be able to launch "kitty". Very useful for people that need to run some commands on the command line if desired. Also aids in troubleshooting.
=> Updated Pegasus to be able to use zip files for ScuumVM and iso files for PS3

apps/pegasus/build/Dockerfile
cat command did not like the indentation in the dockerfile:
1. indentation spaces are written in the tmp file
2. EOF gets ignored
This caused the install command of pegasus to be skipped.
I have removed the indentation in the pegasus install section. This is tested to fix the problem on my PC.
=> Fix the pegasus dockfile

.github/workflows/docker-build-and-publish.yml
When forking I got an Error from the Action 
> Error: buildx failed with: ERROR: failed to build: failed to solve: failed to configure registry cache exporter: invalid reference format: repository name (Skerga/gow/base) must be lowercase
So I added a small step that ensures that `github.repository_owner` and `github.event.pull_request.head.repo.owner.login` are converted to lowercase.
=> Ensure GHCR_NAMESPACE is all lowercase.
